T: 3
act: relu
activation_map: false
amsgrad: false
batchid: 8
batchimage: 6
batchtest: 32
beta1: 0.9
beta2: 0.999
bnneck: false
config: ''
cosine_annealing: false
cpu: false
cutout: false
dampening: 0
data_test: dukemtmc
data_train: dukemtmc
datadir: /content/ReIDataset/
decay_type: step_50_80_110
drop_block: false
epochs: 110
epsilon: 1.0e-08
feat_inference: after
feats: 512
gamma: 0.1
h_ratio: 0.3
height: 384
if_labelsmooth: true
loss: 0.5*CrossEntropy+0.5*MSLoss
lr: 0.0006
lr_decay: 60
margin: 0.7
model: MCMP_n
momentum: 0.9
nGPU: 1
nThread: 4
nesterov: false
num_anchors: 1
num_classes: 751
optimizer: ADAM
parts: 6
pcb_different_lr: true
pool: avg
probability: 0.5
random_erasing: true
reset: false
sampler: true
test_every: 20
w_cosine_annealing: true
w_ratio: 1.0
warmup: constant
weight_decay: 0.0005
width: 128
