T: 3
act: relu
amsgrad: false
batchid: 16
batchimage: 4
batchtest: 32
beta1: 0.9
beta2: 0.999
bnneck: false
config: ''
cpu: false
dampening: 0
data_test: Market1501
data_train: Market1501
datadir: Market-1501-v15.09.15
decay_type: step
epochs: 80
epsilon: 1.0e-08
feat_inference: after
feats: 256
gamma: 0.1
height: 384
if_labelsmooth: false
loss: 1*CrossEntropy+1*Triplet
lr: 0.0002
lr_decay: 60
margin: 1.2
model: MGN
momentum: 0.9
nGPU: 1
nThread: 4
nesterov: false
num_anchors: 1
num_classes: 751
optimizer: ADAM
outdir: out
pool: avg
pre_train: ''
probability: 0.5
random_erasing: false
re_rank: false
reset: false
resume: 0
sampler: true
save_models: false
savedir: saved_models
test_every: 20
test_only: false
warmup: none
weight_decay: 0.0005
width: 128
